POST http://localhost:8080/tasks
Content-Type: application/json

{}

###
# curl -i http://httpbin.org/ip
GET http://httpbin.org/ip

<> 2022-08-30T010615.200.json

###

GET http://localhost:8080/tasks

<> 2022-08-30T005845.200.json
<> 2022-08-30T004959.200.json
<> 2022-08-30T004731.200.json

###
POST http://localhost:8080/tasks
{
  "descripcion": "Aprender React",
  "done": false,
  "dueDate": "2022-10-12"
}

<> 2022-08-30T005628.400.html


###
POST http://localhost:8080/tasks
{
  "descripcion": "Aprender Ingles",
  "done": false,
  "dueDate": "2022-10-12"
}

<> 2022-08-30T005755.400.html

###
GET http://localhost:8080/tasks

<> 2022-08-30T010024.200.json
<> 2022-08-30T005955.404.json

###
POST http://localhost:8080/tasks
Content-Type: application/json
{
  "descripcion": "Aprender Ingles",
  "done": false,
  "dueDate": "2022-10-12"
}

<> 2022-08-30T010340.400.html

###
POST http://localhost:8080/tasks
{
  "descripcion": "Aprender React",
  "done": false,
  "dueDate": "2022-10-12"
}

<> 2022-08-30T005628.400.html


###
POST http://localhost:8080/tasks
{
  "descripcion": "Aprender Ingles",
  "done": false,
  "dueDate": "2022-10-12"
}

<> 2022-08-30T005755.400.html

###
GET http://localhost:8080/tasks

<> 2022-08-30T010024.200.json
<> 2022-08-30T005955.404.json

###
POST http://localhost:8080/tasks
Content-Type: application/json
{
  "descripcion": "Aprender Ingles",
  "done": false,
  "dueDate": "2022-10-12"
}

<> 2022-08-30T010340.400.html

###